services:
  postgres:
    image: postgres:17
    container_name: emailn-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: emailn_dev
      POSTGRES_PASSWORD: "d4#rt6"
      POSTGRES_DB: emailn_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev

volumes:
  postgres_data:
