@baseUrl = http://localhost:3000/campaigns

POST {{baseUrl}}
Content-Type: application/application/json

{
    "name": "mouse 2",
    "content": "change password",
    "emails": ["teste@test.com.br"]
}

### GetByID
GET {{baseUrl}}/{id}
