@baseUrl = http://localhost:3000/campaigns

POST {{baseUrl}}
Content-Type: application/application/json

{
    "name": "mouse 2",
    "content": "change password",
    "emails": ["teste@test.com.br"]
}

### GetByID
GET {{baseUrl}}/d9dmv9le0ol75j7eika0l

### Cancel
PATCH {{baseUrl}}/cancel/d9dmv9le0ol75j7eika

### Delete
DELETE {{baseUrl}}/delete/d9dn0r5e0ol6ov13mctg
