@baseUrl = http://localhost:3000

POST {{baseUrl}}/campaigns
Content-Type: application/application/json

{
    "name": "mouse 2",
    "content": "change password",
    "emails": ["teste@test.com.br"]
}

###
GET {{baseUrl}}/campaigns

